// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $$0 from "./islands/Hero.tsx";
import * as $$1 from "./islands/Products.tsx";
import * as $$2 from "./islands/header/PreHeader.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
  },
  islands: {
    "./islands/Hero.tsx": $$0,
    "./islands/Products.tsx": $$1,
    "./islands/header/PreHeader.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
